name-template: 'Avogadro $RESOLVED_VERSION'
tag-template: '$RESOLVED_VERSION'
categories:
  - title: '✨ Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🚀 Performance Improvements'
    labels:
      - 'speed'
  - title: '🧰 Maintenance'
    labels:
      - 'chore'
      - 'build'
  - title: '📚 Translations'
    labels:
      - 'i18n'
autolabeler:
  - label: 'build'
    branch:
      - '/build\/.+/'
    title:
      - '/build/i'
  - label: 'bug'
    branch:
      - '/fix\/.+/'
    title:
      - '/fix/i'
  - label: 'i18n'
    branch:
      - '/weblate\/.+/'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: minor
template: |
  ## Changes

  $CHANGES

  ## Credits

  Thanks to many contributors, including: $CONTRIBUTORS
  
