/******************************************************************************
  This source file is part of the Avogadro project.
  This source code is released under the 3-Clause BSD License, (see "LICENSE").
******************************************************************************/

#include "plyvisitor.h"

#include <cmath>
#include <cstdint>
#include <cstring>
#include <ostream>
#include <sstream>
#include <vector>

namespace Avogadro::Rendering {

namespace {

// Buffers output and flushes it to the stream in large pieces.
class ChunkWriter
{
public:
  explicit ChunkWriter(std::ostream& out) : m_out(out)
  {
    m_buffer.reserve(kChunk + 64);
  }
  ~ChunkWriter() { flush(); }

  void byte(unsigned char b) { m_buffer.push_back(static_cast<char>(b)); }

  void u32(std::uint32_t value)
  {
    for (int i = 0; i < 4; ++i)
      byte(static_cast<unsigned char>((value >> (8 * i)) & 0xff));
  }

  void f32(float value)
  {
    static_assert(sizeof(float) == 4, "PLY needs 32-bit floats");
    std::uint32_t bits;
    std::memcpy(&bits, &value, 4);
    u32(bits); // IEEE-754 bits, written least significant byte first
  }

  void text(const std::string& s)
  {
    m_buffer.insert(m_buffer.end(), s.begin(), s.end());
  }

  void checkFlush()
  {
    if (m_buffer.size() >= kChunk)
      flush();
  }

  void flush()
  {
    if (!m_buffer.empty()) {
      m_out.write(m_buffer.data(),
                  static_cast<std::streamsize>(m_buffer.size()));
      m_buffer.clear();
    }
  }

private:
  static constexpr size_t kChunk = 1 << 20;
  std::ostream& m_out;
  std::vector<char> m_buffer;
};

} // namespace

PLYVisitor::PLYVisitor(const Camera& c)
  : m_camera(c), m_backgroundColor(255, 255, 255),
    m_ambientColor(100, 100, 100), m_aspectRatio(800.0f / 600.0f)
{
}

PLYVisitor::~PLYVisitor() = default;

void PLYVisitor::setScale(float scale)
{
  if (std::isfinite(scale) && scale > 0.0f)
    m_scale = scale;
}

bool PLYVisitor::write(std::ostream& out) const
{
  size_t vertexCount = 0;
  size_t faceCount = 0;
  for (const auto& mesh : meshes()) {
    vertexCount += mesh.positions.size();
    faceCount += mesh.indices.size() / 3;
  }

  std::ostringstream header;
  header.precision(9);
  header << "ply\n"
         << "format " << (m_binary ? "binary_little_endian" : "ascii")
         << " 1.0\n"
         << "comment generated by Avogadro\n"
         << "comment Avogadro export: center " << m_center[0] << ' '
         << m_center[1] << ' ' << m_center[2] << " angstrom, scale " << m_scale
         << " (output units per angstrom)\n"
         << "element vertex " << vertexCount << '\n'
         << "property float x\n"
         << "property float y\n"
         << "property float z\n"
         << "property float nx\n"
         << "property float ny\n"
         << "property float nz\n"
         << "property uchar red\n"
         << "property uchar green\n"
         << "property uchar blue\n"
         << "property uchar alpha\n"
         << "element face " << faceCount << '\n'
         << "property list uchar uint vertex_indices\n"
         << "end_header\n";

  ChunkWriter writer(out);
  writer.text(header.str());

  if (m_binary) {
    for (const auto& mesh : meshes()) {
      for (size_t i = 0; i < mesh.positions.size(); ++i) {
        const Vector3f p = (mesh.positions[i] - m_center) * m_scale;
        const Vector3f& n = mesh.normals[i];
        const Vector4ub& c = mesh.colors[i];
        for (int k = 0; k < 3; ++k)
          writer.f32(p[k]);
        for (int k = 0; k < 3; ++k)
          writer.f32(n[k]);
        for (int k = 0; k < 4; ++k)
          writer.byte(c[k]);
        writer.checkFlush();
      }
    }
    size_t offset = 0;
    for (const auto& mesh : meshes()) {
      for (size_t i = 0; i + 2 < mesh.indices.size(); i += 3) {
        writer.byte(3);
        for (size_t k = 0; k < 3; ++k)
          writer.u32(static_cast<std::uint32_t>(mesh.indices[i + k] + offset));
        writer.checkFlush();
      }
      offset += mesh.positions.size();
    }
  } else {
    for (const auto& mesh : meshes()) {
      for (size_t i = 0; i < mesh.positions.size(); ++i) {
        const Vector3f p = (mesh.positions[i] - m_center) * m_scale;
        const Vector3f& n = mesh.normals[i];
        const Vector4ub& c = mesh.colors[i];
        std::ostringstream line;
        line.precision(9);
        line << p[0] << ' ' << p[1] << ' ' << p[2] << ' ' << n[0] << ' ' << n[1]
             << ' ' << n[2] << ' ' << static_cast<int>(c[0]) << ' '
             << static_cast<int>(c[1]) << ' ' << static_cast<int>(c[2]) << ' '
             << static_cast<int>(c[3]) << '\n';
        writer.text(line.str());
        writer.checkFlush();
      }
    }
    size_t offset = 0;
    for (const auto& mesh : meshes()) {
      for (size_t i = 0; i + 2 < mesh.indices.size(); i += 3) {
        writer.text("3 " + std::to_string(mesh.indices[i] + offset) + ' ' +
                    std::to_string(mesh.indices[i + 1] + offset) + ' ' +
                    std::to_string(mesh.indices[i + 2] + offset) + '\n');
        writer.checkFlush();
      }
      offset += mesh.positions.size();
    }
  }

  writer.flush();
  out.flush();
  return static_cast<bool>(out);
}

std::string PLYVisitor::end()
{
  std::ostringstream out;
  write(out);
  return out.str();
}

} // namespace Avogadro::Rendering
