name: clang-format Check
on: [push]
jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: clang-format style check for C++ / C code.
      uses: ghutchis/clang-format-diff-action@master
      with:
        source: 'avogadro'
        extensions: 'h,cpp'
        clangFormatVersion: 6
